version: '3.7'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        # We run a pip install to catch cases where requirements were added but a Docker build hasn't run yet
        command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
        working_dir: /usr/local/site/backend
        volumes:
        - ./backend/:/usr/local/site/backend/
        - ../certificates/private_keys.py:/usr/local/site/backend/carebackend/private_keys.py
        ports:
        - 8000:8000
        env_file:
        - ./.env.dev
